### PR TITLE
Updates for Kerbalism Compatibility

### PR DESCRIPTION
**Pull request by CaesarVincens**
Descriptions of changes in each file, mostly updating resources. #11 

Further balancing is probably warranted, particularly for the storage template.

The bonus science transmission will require an update of either the Wild Blue plugin to make use of the Kerbalism Antenna Module which replaces the stock ModuleDataTransmitter if the Signal feature is enabled (not unlike using RemoteTech, i.e. custom Antenna module).

### CODE REVIEW

**Comment by schrema** [comment]
Please consider that Atmosphere and WasteAtmosphere needs to added to the resourcesToKeep configuration too. Kerbalism uses this resources for the habitat volume and pressure control.
I'm new at GitHub and if I had idea how to make suggestions to your commits, I would do it by myself. Maybe I will find a way.

**Comment by schrema** [comment]
I found out another thing. Kerbalism uses some pseudo resources, used by ProcessController. They must be added to the resourcesToKeep config too.

_Scrubber;_PressureControl;_WaterRecycler;_WasteProcessor

**Comment by CaesarVincens** [comment]
Schrema, I'd want to talk to ShotgunNinja, creator of Kerbalism, more on that, but some of the resources are added dynamically by Kerbalism's dll/features and are not present on the pod at all times. It may be worth adding those to the WBI/MOLE configs, but I haven't encountered a problem with that yet while playing with both.

**Comment by schrema** [comment]
I've played with the configs a little bit in VAB. Without the additonal configs, doesn't work Kerbalism fine. For example, when you change the configuration of a part via the WBI Module switch in VAB, all the pseudo resources are gone. Kerbalism adds Atmosphere and WasteAtmosphere only for new parts and _Scrubber, _PressureControl, _WaterRecycler and _WasteProcessor only after changing the Kerb. Pod Configuration. Therefore the habitat volumen is set to zero, cause of Atmosphere and WasteAtmosphere is missing and so on. I've used KerbalEngineer to check the resources.
Maybe Shotgun Ninja can say exactly when resources are added and removed.

**Comment by ShotgunNinja** [comment]
Habitat resources (Shielding, Atmosphere and WasteAtmosphere) are added dynamically by the Habitat module. Every time the module is initialized (when added in the VAB, or when the vessel is loaded) it check if capacity for these resources is present, and if not it automatically add them.

ProcessController module does the same with the process-specific pseudo-resources (like _WaterRecycler, _Scrubber, and so on).

I've tried what @schrema said, and is true. When you hit 'reconfigure' in the MOLE ui, it will reset the resources mentioned above (probably because they aren't in the 'resourcesToKeep' white list).

However, as soon as the Habitat/ProcessController modules are re-initialized (when vessel is launched, or if the vessel is loaded again in VAB), these resources are re-added automatically. That is probably why @CaesarVincens didn't notice any issue, because there isn't any as soon as you launch the vessel.

So the only effect of this for the user is that, when it hit 'reconfigure' in the MOLE ui, some planner calculations are wrong until the vessel is reloaded.

Best regards.

**Comment by Angel-125** [comment]
Sounds like the issues are resolved then? If so, I'll merge the pull request. Thanks for making the updates. :)

**Pull request closed without merging**
